name: snoutsaver
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  form_field_validator: ^1.1.0
  intl: ^0.19.0
  password_validated_field: ^0.0.3
  step_progress_indicator: ^1.0.2
  google_fonts: ^6.2.0
  http: ^1.2.2
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
